
import type { LucideIcon } from "lucide-react";
import {
  Landmark, TrendingUp, Percent, Home, BadgePercent, PiggyBank, Umbrella, Repeat, FileText, Sigma, Target, Scale, LineChart, Coins, Receipt, Award, Calculator as CalculatorIconProp, CandlestickChart, Gauge, Car, PercentSquare, Wallet, ListChecks, Banknote, Milestone, Wallet2, Building2, ShoppingCart, Hotel, Users2, Building, Users, CreditCard, WalletCards, Undo, GraduationCap, School, CircleDollarSign, ShieldCheck, BookOpen, TrendingDown, Repeat1, Ratio, Divide, GitCompare, Undo2, Utensils, Flame, HeartPulse, BrainCircuit, PieChart, Baby, CalendarDays, Footprints, Wheat, Dumbbell, Droplet, Activity, TestTube2 as TestTube, PersonStanding, Ruler as RulerIcon, GlassWater, Frown, SquareFunction, MinusSquare, Triangle, Box, Dices, ListOrdered, AlertCircle, Superscript, Binary, Hash, FunctionSquare, Square, BarChart, Braces, Route, Circle, BoxSelect, TriangleRight, Variable, ArrowRightLeft, Rows, Clock, BookMarked, Construction, Network as NetworkIcon, Shirt, LockKeyhole, Dice5, Fuel, Zap, Thermometer as ThermometerIcon, Globe, Heart as HeartIcon, Cog, CircuitBoard, Lightbulb, Beaker, Atom, Flag, Moon, CircleDot, HardHat as HardHatIcon, Sprout, Boxes, Wind, ThermometerSun, Droplets, Wifi, Timer, Weight as WeightIcon, Search, Shapes, FlaskConical, Bookmark // Keep necessary imports
} from 'lucide-react'; // Use specific imports

// Define broader categories
export type CalculatorCategory = "Financial" | "Fitness & Health" | "Math" | "Other";

export interface CalculatorInfo {
  slug: string;
  name: string;
  description: string; // Add a short description for each calculator
  category: CalculatorCategory;
  icon: LucideIcon;
  seoTitle?: string; // Optional: Specific SEO title for the calculator page
  seoDescription?: string; // Optional: Specific meta description
  seoKeywords?: string[]; // Optional: Keywords for meta tags
}

// Updated list of calculators with descriptions and corrected icons
export const CALCULATORS: CalculatorInfo[] = [
  // Financial Calculators
   { slug: 'loan-payment', name: 'Loan Payment', description: 'Calculate monthly loan payments.', icon: Landmark, category: 'Financial' },
   { slug: 'investment-growth', name: 'Investment Growth', description: 'Project future value of investments.', icon: TrendingUp, category: 'Financial' },
   { slug: 'compound-interest', name: 'Compound Interest', description: 'Calculate interest compounded over time.', icon: Percent, category: 'Financial' },
   { slug: 'mortgage', name: 'Mortgage', description: 'Estimate mortgage payments.', icon: Home, category: 'Financial' },
   { slug: 'apr', name: 'APR', description: 'Calculate Annual Percentage Rate.', icon: BadgePercent, category: 'Financial' },
   { slug: 'savings', name: 'Savings', description: 'Plan your savings goals.', icon: PiggyBank, category: 'Financial' },
   { slug: 'retirement', name: 'Retirement', description: 'Estimate retirement savings needs.', icon: Umbrella, category: 'Financial' },
   { slug: 'annuity', name: 'Annuity', description: 'Calculate annuity payments or value.', icon: Repeat, category: 'Financial' },
   { slug: 'bond-yield', name: 'Bond Yield', description: 'Calculate yield on bonds.', icon: FileText, category: 'Financial' },
   { slug: 'npv', name: 'Net Present Value (NPV)', description: 'Calculate NPV for investments.', icon: Sigma, category: 'Financial' },
   { slug: 'irr', name: 'Internal Rate of Return (IRR)', description: 'Calculate IRR for investments.', icon: Target, category: 'Financial' },
   { slug: 'breakeven', name: 'Breakeven Point', description: 'Determine the breakeven point.', icon: Scale, category: 'Financial' },
   { slug: 'profit-margin', name: 'Profit Margin', description: 'Calculate profit margins.', icon: LineChart, category: 'Financial' },
   { slug: 'currency-converter', name: 'Currency Converter', description: 'Convert between currencies.', icon: Coins, category: 'Financial' },
   { slug: 'tax', name: 'Tax Calculator', description: 'Estimate income or other taxes.', icon: Receipt, category: 'Financial' },
   { slug: 'gratuity', name: 'Gratuity Calculator', description: 'Calculate gratuity amounts.', icon: Award, category: 'Financial' },
   { slug: 'emi', name: 'EMI Calculator', description: 'Calculate Equated Monthly Installments.', icon: CalculatorIconProp, category: 'Financial' },
   { slug: 'sip', name: 'SIP Calculator', description: 'Estimate returns on SIP investments.', icon: CandlestickChart, category: 'Financial' },
   { slug: 'inflation', name: 'Inflation Calculator', description: 'Adjust values for inflation.', icon: Gauge, category: 'Financial' },
   //{ slug: 'tariff-calculator', name: 'Tariff Calculator', description: 'Calculate import/export tariffs.', icon: FileText, category: 'Financial' }, // Removed
   { slug: 'auto-loan', name: 'Auto Loan Calculator', description: 'Calculate car loan payments.', icon: Car, category: 'Financial' },
   { slug: 'interest-calculator', name: 'Interest Calculator', description: 'Calculate simple or compound interest.', icon: PercentSquare, category: 'Financial' },
   { slug: 'payment-calculator', name: 'Payment Calculator', description: 'Calculate loan or lease payments.', icon: Wallet, category: 'Financial' },
   { slug: 'amortization-calculator', name: 'Amortization Calculator', description: 'View loan amortization schedule.', icon: ListChecks, category: 'Financial' },
   { slug: 'finance-calculator', name: 'Finance Calculator', description: 'General financial calculations.', icon: Banknote, category: 'Financial' },
   { slug: 'mortgage-payoff', name: 'Mortgage Payoff Calculator', description: 'Plan early mortgage payoff.', icon: Milestone, category: 'Financial' },
   //{ slug: 'income-tax-calculator', name: 'Income Tax Calculator', description: 'Estimate your income tax.', icon: Receipt, category: 'Financial' }, // No component
   { slug: 'salary-calculator', name: 'Salary Calculator', description: 'Calculate net salary after deductions.', icon: Wallet2, category: 'Financial' },
   { slug: '401k-calculator', name: '401k Calculator', description: 'Estimate 401(k) growth.', icon: Building2, category: 'Financial' },
   { slug: 'interest-rate-calculator', name: 'Interest Rate Calculator', description: 'Calculate effective interest rates.', icon: PercentSquare, category: 'Financial' },
   { slug: 'sales-tax-calculator', name: 'Sales Tax Calculator', description: 'Calculate sales tax amount.', icon: ShoppingCart, category: 'Financial' },
   { slug: 'house-affordability', name: 'House Affordability Calculator', description: 'Estimate affordable house price.', icon: Home, category: 'Financial' },
   { slug: 'rent-calculator', name: 'Rent Calculator', description: 'Calculate rent affordability.', icon: Hotel, category: 'Financial' },
   { slug: 'marriage-tax-calculator', name: 'Marriage Tax Calculator', description: 'Estimate tax implications of marriage.', icon: Users2, category: 'Financial' },
   { slug: 'estate-tax-calculator', name: 'Estate Tax Calculator', description: 'Estimate potential estate tax.', icon: Landmark, category: 'Financial' },
   { slug: 'pension-calculator', name: 'Pension Calculator', description: 'Estimate pension income.', icon: Building, category: 'Financial' },
   { slug: 'social-security-calculator', name: 'Social Security Calculator', description: 'Estimate social security benefits.', icon: Users, category: 'Financial' },
   { slug: 'annuity-payout-calculator', name: 'Annuity Payout Calculator', description: 'Calculate annuity payout amounts.', icon: Repeat, category: 'Financial' },
   { slug: 'credit-card-calculator', name: 'Credit Card Calculator', description: 'Calculate credit card payments/interest.', icon: CreditCard, category: 'Financial' },
   { slug: 'credit-cards-payoff-calculator', name: 'Credit Cards Payoff Calculator', description: 'Plan credit card payoff strategy.', icon: CreditCard, category: 'Financial' },
   { slug: 'debt-payoff-calculator', name: 'Debt Payoff Calculator', description: 'Plan general debt payoff.', icon: WalletCards, category: 'Financial' },
   { slug: 'debt-consolidation-calculator', name: 'Debt Consolidation Calculator', description: 'Evaluate debt consolidation options.', icon: WalletCards, category: 'Financial' },
   { slug: 'repayment-calculator', name: 'Repayment Calculator', description: 'Calculate loan repayment schedules.', icon: Undo, category: 'Financial' },
   { slug: 'student-loan-calculator', name: 'Student Loan Calculator', description: 'Calculate student loan payments.', icon: GraduationCap, category: 'Financial' },
   { slug: 'college-cost-calculator', name: 'College Cost Calculator', description: 'Estimate total college costs.', icon: School, category: 'Financial' },
   { slug: 'simple-interest-calculator', name: 'Simple Interest Calculator', description: 'Calculate simple interest.', icon: PercentSquare, category: 'Financial' },
   { slug: 'cd-calculator', name: 'CD Calculator', description: 'Calculate Certificate of Deposit earnings.', icon: CircleDollarSign, category: 'Financial' },
   { slug: 'bond-calculator', name: 'Bond Calculator', description: 'Calculate bond price/yield.', icon: FileText, category: 'Financial' },
   { slug: 'roth-ira-calculator', name: 'Roth IRA Calculator', description: 'Estimate Roth IRA growth.', icon: ShieldCheck, category: 'Financial' },
   { slug: 'ira-calculator', name: 'IRA Calculator', description: 'Estimate traditional IRA growth.', icon: ShieldCheck, category: 'Financial' },
   { slug: 'rmd-calculator', name: 'RMD Calculator', description: 'Calculate Required Minimum Distributions.', icon: BookOpen, category: 'Financial' },
   { slug: 'vat-calculator', name: 'VAT Calculator', description: 'Calculate Value Added Tax.', icon: Receipt, category: 'Financial' },
   { slug: 'cash-back-or-low-interest', name: 'Cash Back or Low Interest', description: 'Compare financing options.', icon: Banknote, category: 'Financial' },
   { slug: 'auto-lease-calculator', name: 'Auto Lease Calculator', description: 'Calculate car lease payments.', icon: Car, category: 'Financial' },
   { slug: 'depreciation-calculator', name: 'Depreciation Calculator', description: 'Calculate asset depreciation.', icon: TrendingDown, category: 'Financial' },
   { slug: 'average-return-calculator', name: 'Average Return Calculator', description: 'Calculate average investment return.', icon: Repeat1, category: 'Financial' },
   { slug: 'margin-calculator', name: 'Margin Calculator', description: 'Calculate profit margins.', icon: Ratio, category: 'Financial' },
   { slug: 'discount-calculator', name: 'Discount Calculator', description: 'Calculate discounts and sale prices.', icon: Percent, category: 'Financial' },
   { slug: 'business-loan-calculator', name: 'Business Loan Calculator', description: 'Calculate business loan payments.', icon: Building, category: 'Financial' },
   { slug: 'debt-to-income-ratio', name: 'Debt-to-Income Ratio Calculator', description: 'Calculate your DTI ratio.', icon: Divide, category: 'Financial' },
   { slug: 'real-estate-calculator', name: 'Real Estate Calculator', description: 'Analyze real estate investments.', icon: Building2, category: 'Financial' },
   { slug: 'take-home-paycheck-calculator', name: 'Take-Home-Paycheck Calculator', description: 'Calculate net take-home pay.', icon: Wallet2, category: 'Financial' },
   { slug: 'personal-loan-calculator', name: 'Personal Loan Calculator', description: 'Calculate personal loan payments.', icon: Landmark, category: 'Financial' },
   { slug: 'lease-calculator', name: 'Lease Calculator', description: 'Calculate lease payments.', icon: FileText, category: 'Financial' },
   { slug: 'refinance-calculator', name: 'Refinance Calculator', description: 'Evaluate mortgage refinance options.', icon: Home, category: 'Financial' },
   { slug: 'budget-calculator', name: 'Budget Calculator', description: 'Create and manage a budget.', icon: WalletCards, category: 'Financial' },
   { slug: 'rental-property-calculator', name: 'Rental Property Calculator', description: 'Analyze rental property investments.', icon: Hotel, category: 'Financial' },
   { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Calculate Return on Investment.', icon: TrendingUp, category: 'Financial' },
   { slug: 'fha-loan-calculator', name: 'FHA Loan Calculator', description: 'Calculate FHA loan payments.', icon: Home, category: 'Financial' },
   { slug: 'va-mortgage-calculator', name: 'VA Mortgage Calculator', description: 'Calculate VA mortgage payments.', icon: Home, category: 'Financial' },
   { slug: 'down-payment-calculator', name: 'Down Payment Calculator', description: 'Calculate mortgage down payment.', icon: PiggyBank, category: 'Financial' },
   //{ slug: 'rent-vs-buy-calculator', name: 'Rent vs. Buy Calculator', description: 'Compare the costs of renting versus buying a home.', icon: GitCompare, category: 'Financial' }, // Component commented out
   { slug: 'payback-period-calculator', name: 'Payback Period Calculator', description: 'Calculate investment payback period.', icon: Undo2, category: 'Financial' },
   { slug: 'present-value-calculator', name: 'Present Value Calculator', description: 'Calculate present value of future cash flows.', icon: Sigma, category: 'Financial' },
   { slug: 'future-value-calculator', name: 'Future Value Calculator', description: 'Calculate future value of investments.', icon: Sigma, category: 'Financial' },
   { slug: 'commission-calculator', name: 'Commission Calculator', description: 'Calculate sales commissions.', icon: Percent, category: 'Financial' },
   { slug: 'mortgage-calculator-uk', name: 'Mortgage Calculator UK', description: 'UK-specific mortgage calculations.', icon: Home, category: 'Financial' },
   { slug: 'canadian-mortgage-calculator', name: 'Canadian Mortgage Calculator', description: 'Canada-specific mortgage calculations.', icon: Home, category: 'Financial' },
   { slug: 'mortgage-amortization-calculator', name: 'Mortgage Amortization Calculator', description: 'View mortgage amortization schedule.', icon: ListChecks, category: 'Financial' },
   { slug: 'percent-off-calculator', name: 'Percent Off Calculator', description: 'Calculate price after percentage discount.', icon: Percent, category: 'Financial' },

    // Fitness and Health Calculators
   { slug: 'bmi-calculator', name: 'BMI Calculator', description: 'Calculate Body Mass Index.', icon: WeightIcon, category: 'Fitness & Health' },
   { slug: 'calorie-calculator', name: 'Calorie Calculator', description: 'Estimate daily calorie needs.', icon: Flame, category: 'Fitness & Health' },
   { slug: 'body-fat-calculator', name: 'Body Fat Calculator', description: 'Estimate body fat percentage.', icon: HeartPulse, category: 'Fitness & Health' },
   { slug: 'bmr-calculator', name: 'BMR Calculator', description: 'Calculate Basal Metabolic Rate.', icon: BrainCircuit, category: 'Fitness & Health' },
   { slug: 'macro-calculator', name: 'Macro Calculator', description: 'Calculate macronutrient needs.', icon: PieChart, category: 'Fitness & Health' },
   { slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', description: 'Estimate ideal body weight.', icon: WeightIcon, category: 'Fitness & Health' },
   { slug: 'pregnancy-calculator', name: 'Pregnancy Calculator', description: 'Estimate due date and track pregnancy.', icon: Baby, category: 'Fitness & Health' },
   { slug: 'pregnancy-weight-gain', name: 'Pregnancy Weight Gain', description: 'Track healthy pregnancy weight gain.', icon: WeightIcon, category: 'Fitness & Health' },
   { slug: 'pregnancy-conception', name: 'Pregnancy Conception', description: 'Estimate conception date.', icon: CalendarDays, category: 'Fitness & Health' },
   { slug: 'due-date-calculator', name: 'Due Date Calculator', description: 'Calculate estimated due date.', icon: CalendarDays, category: 'Fitness & Health' },
   { slug: 'pace-calculator', name: 'Pace Calculator', description: 'Calculate running/walking pace.', icon: Footprints, category: 'Fitness & Health' },
   { slug: 'army-body-fat-calculator', name: 'Army Body Fat Calculator', description: 'US Army body fat calculation.', icon: HeartPulse, category: 'Fitness & Health' },
   { slug: 'carbohydrate-calculator', name: 'Carbohydrate Calculator', description: 'Estimate carbohydrate needs.', icon: Wheat, category: 'Fitness & Health' },
   { slug: 'lean-body-mass', name: 'Lean Body Mass Calculator', description: 'Calculate lean body mass.', icon: Dumbbell, category: 'Fitness & Health' },
   { slug: 'healthy-weight-calculator', name: 'Healthy Weight Calculator', description: 'Determine healthy weight range.', icon: WeightIcon, category: 'Fitness & Health' },
   { slug: 'calories-burned-calculator', name: 'Calories Burned Calculator', description: 'Estimate calories burned during activities.', icon: Flame, category: 'Fitness & Health' },
   { slug: 'one-rep-max-calculator', name: 'One Rep Max Calculator', description: 'Estimate your one-rep max lift.', icon: Dumbbell, category: 'Fitness & Health' },
   { slug: 'protein-calculator', name: 'Protein Calculator', description: 'Estimate daily protein needs.', icon: Utensils, category: 'Fitness & Health' },
   { slug: 'fat-intake-calculator', name: 'Fat Intake Calculator', description: 'Estimate daily fat intake.', icon: Droplet, category: 'Fitness & Health' },
   { slug: 'tdee-calculator', name: 'TDEE Calculator', description: 'Calculate Total Daily Energy Expenditure.', icon: Activity, category: 'Fitness & Health' },
   { slug: 'ovulation-calculator', name: 'Ovulation Calculator', description: 'Predict ovulation period.', icon: CalendarDays, category: 'Fitness & Health' },
   { slug: 'conception-calculator', name: 'Conception Calculator', description: 'Estimate conception date.', icon: CalendarDays, category: 'Fitness & Health' },
   { slug: 'period-calculator', name: 'Period Calculator', description: 'Track menstrual cycle.', icon: CalendarDays, category: 'Fitness & Health' },
   { slug: 'gfr-calculator', name: 'GFR Calculator', description: 'Estimate Glomerular Filtration Rate.', icon: TestTube, category: 'Fitness & Health' },
   { slug: 'body-type-calculator', name: 'Body Type Calculator', description: 'Determine your body type.', icon: PersonStanding, category: 'Fitness & Health' },
   { slug: 'body-surface-area', name: 'Body Surface Area Calculator', description: 'Calculate body surface area.', icon: RulerIcon, category: 'Fitness & Health' },
   { slug: 'bac-calculator', name: 'BAC Calculator', description: 'Estimate Blood Alcohol Content.', icon: GlassWater, category: 'Fitness & Health' },
   //{ slug: 'anorexic-bmi-calculator', name: 'Anorexic BMI Calculator', description: 'BMI calculation for specific conditions.', icon: Frown, category: 'Fitness & Health' }, // Removed
   { slug: 'weight-watcher-points', name: 'Weight Watcher Points', description: 'Calculate Weight Watchers points.', icon: CalculatorIconProp, category: 'Fitness & Health' },
   //{ slug: 'overweight-calculator', name: 'Overweight Calculator', description: 'Assess weight status.', icon: WeightIcon, category: 'Fitness & Health' }, // Covered by BMI

   // Math Calculators
   { slug: 'scientific-calculator', name: 'Scientific Calculator', description: 'Perform advanced calculations.', icon: FlaskConical, category: 'Math' },
   { slug: 'fraction-calculator', name: 'Fraction Calculator', description: 'Perform operations with fractions.', icon: MinusSquare, category: 'Math' },
   { slug: 'percentage-calculator', name: 'Percentage Calculator', description: 'Calculate percentages.', icon: Percent, category: 'Math' },
   { slug: 'triangle-calculator', name: 'Triangle Calculator', description: 'Calculate properties of triangles.', icon: Triangle, category: 'Math' },
   { slug: 'volume-calculator', name: 'Volume Calculator', description: 'Calculate volume of shapes.', icon: Box, category: 'Math' },
   { slug: 'standard-deviation', name: 'Standard Deviation Calculator', description: 'Calculate standard deviation.', icon: Sigma, category: 'Math' },
   { slug: 'random-number-generator', name: 'Random Number Generator', description: 'Generate random numbers.', icon: Dices, category: 'Math' },
   { slug: 'number-sequence', name: 'Number Sequence Calculator', description: 'Analyze number sequences.', icon: ListOrdered, category: 'Math' },
   { slug: 'percent-error-calculator', name: 'Percent Error Calculator', description: 'Calculate percentage error.', icon: AlertCircle, category: 'Math' },
   { slug: 'exponent-calculator', name: 'Exponent Calculator', description: 'Calculate exponents.', icon: Superscript, category: 'Math' },
   { slug: 'binary-calculator', name: 'Binary Calculator', description: 'Perform binary operations.', icon: Binary, category: 'Math' },
   { slug: 'hex-calculator', name: 'Hex Calculator', description: 'Perform hexadecimal operations.', icon: Hash, category: 'Math' },
   { slug: 'half-life-calculator', name: 'Half-Life Calculator', description: 'Calculate half-life.', icon: TestTube, category: 'Math' },
   { slug: 'quadratic-formula', name: 'Quadratic Formula Calculator', description: 'Solve quadratic equations.', icon: SquareFunction, category: 'Math' },
   { slug: 'slope-calculator', name: 'Slope Calculator', description: 'Calculate slope of a line.', icon: LineChart, category: 'Math' }, // Changed icon
   { slug: 'log-calculator', name: 'Log Calculator', description: 'Calculate logarithms.', icon: FunctionSquare, category: 'Math' },
   { slug: 'area-calculator', name: 'Area Calculator', description: 'Calculate area of shapes.', icon: Square, category: 'Math' },
   { slug: 'sample-size-calculator', name: 'Sample Size Calculator', description: 'Determine required sample size.', icon: Users, category: 'Math' },
   { slug: 'probability-calculator', name: 'Probability Calculator', description: 'Calculate probabilities.', icon: Ratio, category: 'Math' },
   { slug: 'statistics-calculator', name: 'Statistics Calculator', description: 'Perform statistical calculations.', icon: BarChart, category: 'Math' },
   { slug: 'mean-median-mode-range', name: 'Mean, Median, Mode, Range', description: 'Calculate common statistics.', icon: Sigma, category: 'Math' },
   { slug: 'permutation-combination', name: 'Permutation & Combination', description: 'Calculate permutations/combinations.', icon: Braces, category: 'Math' },
   { slug: 'z-score-calculator', name: 'Z-score Calculator', description: 'Calculate Z-scores.', icon: Sigma, category: 'Math' },
   { slug: 'confidence-interval', name: 'Confidence Interval Calculator', description: 'Calculate confidence intervals.', icon: Sigma, category: 'Math' },
   { slug: 'ratio-calculator', name: 'Ratio Calculator', description: 'Simplify and compare ratios.', icon: Ratio, category: 'Math' },
   { slug: 'distance-calculator', name: 'Distance Calculator', description: 'Calculate distance between points.', icon: Route, category: 'Math' },
   { slug: 'circle-calculator', name: 'Circle Calculator', description: 'Calculate properties of circles.', icon: Circle, category: 'Math' },
   { slug: 'surface-area-calculator', name: 'Surface Area Calculator', description: 'Calculate surface area of shapes.', icon: BoxSelect, category: 'Math' },
   { slug: 'pythagorean-theorem', name: 'Pythagorean Theorem', description: 'Use the Pythagorean theorem.', icon: TriangleRight, category: 'Math' },
   { slug: 'right-triangle-calculator', name: 'Right Triangle Calculator', description: 'Solve right triangles.', icon: TriangleRight, category: 'Math' },
   { slug: 'root-calculator', name: 'Root Calculator', description: 'Calculate square/cube roots.', icon: FunctionSquare, category: 'Math' },
   { slug: 'least-common-multiple', name: 'Least Common Multiple (LCM)', description: 'Find the least common multiple.', icon: Variable, category: 'Math' },
   { slug: 'greatest-common-factor', name: 'Greatest Common Factor (GCF)', description: 'Find the greatest common factor.', icon: Variable, category: 'Math' },
   { slug: 'factor-calculator', name: 'Factor Calculator', description: 'Find factors of a number.', icon: Variable, category: 'Math' },
   { slug: 'rounding-calculator', name: 'Rounding Calculator', description: 'Round numbers to desired precision.', icon: ArrowRightLeft, category: 'Math' },
   { slug: 'matrix-calculator', name: 'Matrix Calculator', description: 'Perform matrix operations.', icon: Rows, category: 'Math' },
   { slug: 'scientific-notation', name: 'Scientific Notation Calculator', description: 'Convert to/from scientific notation.', icon: Superscript, category: 'Math' },
   { slug: 'big-number-calculator', name: 'Big Number Calculator', description: 'Calculate with very large numbers.', icon: CalculatorIconProp, category: 'Math' },
   { slug: 'prime-factorization', name: 'Prime Factorization', description: 'Find prime factors of a number.', icon: Variable, category: 'Math' },
   { slug: 'common-factor-calculator', name: 'Common Factor Calculator', description: 'Find common factors.', icon: Variable, category: 'Math' },
   { slug: 'basic-calculator', name: 'Basic Calculator', description: 'Perform basic arithmetic.', icon: CalculatorIconProp, category: 'Math' },
   { slug: 'long-division-calculator', name: 'Long Division Calculator', description: 'Perform long division.', icon: Divide, category: 'Math' },
   { slug: 'average-calculator', name: 'Average Calculator', description: 'Calculate the average of numbers.', icon: Sigma, category: 'Math' },
   { slug: 'p-value-calculator', name: 'P-value Calculator', description: 'Calculate p-values for statistical tests.', icon: Sigma, category: 'Math' },

   // Other Calculators
   { slug: 'age-calculator', name: 'Age Calculator', description: 'Calculate age based on birth date.', icon: CalendarDays, category: 'Other' },
   { slug: 'date-calculator', name: 'Date Calculator', description: 'Calculate duration between dates.', icon: CalendarDays, category: 'Other' },
   { slug: 'time-calculator', name: 'Time Calculator', description: 'Perform calculations with time values.', icon: Clock, category: 'Other' },
   { slug: 'hours-calculator', name: 'Hours Calculator', description: 'Calculate total hours worked.', icon: Clock, category: 'Other' },
   { slug: 'gpa-calculator', name: 'GPA Calculator', description: 'Calculate Grade Point Average.', icon: GraduationCap, category: 'Other' },
   { slug: 'grade-calculator', name: 'Grade Calculator', description: 'Calculate course or final grades.', icon: BookMarked, category: 'Other' },
   { slug: 'height-calculator', name: 'Height Calculator', description: 'Convert between height units.', icon: RulerIcon, category: 'Other' },
   { slug: 'concrete-calculator', name: 'Concrete Calculator', description: 'Estimate concrete volume needed.', icon: Construction, category: 'Other' },
   { slug: 'ip-subnet-calculator', name: 'IP Subnet Calculator', description: 'Calculate network subnets.', icon: NetworkIcon, category: 'Other' },
   { slug: 'bra-size-calculator', name: 'Bra Size Calculator', description: 'Estimate bra size.', icon: Shirt, category: 'Other' },
   { slug: 'password-generator', name: 'Password Generator', description: 'Generate secure passwords.', icon: LockKeyhole, category: 'Other' },
   { slug: 'dice-roller', name: 'Dice Roller', description: 'Roll virtual dice.', icon: Dice5, category: 'Other' },
   { slug: 'conversion-calculator', name: 'Conversion Calculator', description: 'Convert various units.', icon: ArrowRightLeft, category: 'Other' },
   { slug: 'fuel-cost-calculator', name: 'Fuel Cost Calculator', description: 'Estimate fuel costs for trips.', icon: Fuel, category: 'Other' },
   { slug: 'voltage-drop-calculator', name: 'Voltage Drop Calculator', description: 'Calculate voltage drop in circuits.', icon: Zap, category: 'Other' },
   { slug: 'btu-calculator', name: 'BTU Calculator', description: 'Estimate heating/cooling needs.', icon: ThermometerIcon, category: 'Other' },
   { slug: 'square-footage-calculator', name: 'Square Footage Calculator', description: 'Calculate area in square feet.', icon: Square, category: 'Other' },
   { slug: 'time-card-calculator', name: 'Time Card Calculator', description: 'Calculate work hours from time cards.', icon: Clock, category: 'Other' },
   { slug: 'time-zone-calculator', name: 'Time Zone Calculator', description: 'Convert between time zones.', icon: Globe, category: 'Other' },
   { slug: 'love-calculator', name: 'Love Calculator', description: 'A fun compatibility calculator.', icon: HeartIcon, category: 'Other' },
   { slug: 'gdp-calculator', name: 'GDP Calculator', description: 'Calculate Gross Domestic Product.', icon: Globe, category: 'Other' },
   { slug: 'gas-mileage-calculator', name: 'Gas Mileage Calculator', description: 'Calculate fuel efficiency.', icon: Gauge, category: 'Other' },
   { slug: 'horsepower-calculator', name: 'Horsepower Calculator', description: 'Calculate horsepower.', icon: Activity, category: 'Other' },
   { slug: 'engine-horsepower-calculator', name: 'Engine Horsepower Calculator', description: 'Calculate engine horsepower.', icon: Cog, category: 'Other' },
   { slug: 'stair-calculator', name: 'Stair Calculator', description: 'Calculate stair dimensions.', icon: Milestone, category: 'Other' }, // Changed icon
   { slug: 'resistor-calculator', name: 'Resistor Calculator', description: 'Calculate resistor color codes/values.', icon: CircuitBoard, category: 'Other' },
   { slug: 'ohms-law-calculator', name: 'Ohm\'s Law Calculator', description: 'Use Ohm\'s law for calculations.', icon: Lightbulb, category: 'Other' },
   { slug: 'electricity-calculator', name: 'Electricity Calculator', description: 'Estimate electricity cost/usage.', icon: Zap, category: 'Other' },
   { slug: 'tip-calculator', name: 'Tip Calculator', description: 'Calculate tips and split bills.', icon: Percent, category: 'Other' }, // Changed icon
   { slug: 'mileage-calculator', name: 'Mileage Calculator', description: 'Calculate distance traveled.', icon: Route, category: 'Other' },
   { slug: 'density-calculator', name: 'Density Calculator', description: 'Calculate density.', icon: Scale, category: 'Other' }, // Changed icon
   { slug: 'mass-calculator', name: 'Mass Calculator', description: 'Calculate mass.', icon: WeightIcon, category: 'Other' },
   { slug: 'weight-calculator', name: 'Weight Calculator', description: 'Calculate weight on different planets.', icon: WeightIcon, category: 'Other' },
   { slug: 'speed-calculator', name: 'Speed Calculator', description: 'Calculate speed, distance, or time.', icon: Gauge, category: 'Other' },
   { slug: 'molarity-calculator', name: 'Molarity Calculator', description: 'Calculate molarity of solutions.', icon: Beaker, category: 'Other' },
   { slug: 'molecular-weight-calculator', name: 'Molecular Weight Calculator', description: 'Calculate molecular weight.', icon: Atom, category: 'Other' },
   { slug: 'roman-numeral-converter', name: 'Roman Numeral Converter', description: 'Convert numbers to Roman numerals.', icon: Hash, category: 'Other' },
   { slug: 'golf-handicap-calculator', name: 'Golf Handicap Calculator', description: 'Calculate golf handicap.', icon: Flag, category: 'Other' },
   { slug: 'sleep-calculator', name: 'Sleep Calculator', description: 'Calculate optimal sleep times.', icon: Moon, category: 'Other' },
   { slug: 'tire-size-calculator', name: 'Tire Size Calculator', description: 'Compare tire sizes.', icon: CircleDot, category: 'Other' },
   { slug: 'roofing-calculator', name: 'Roofing Calculator', description: 'Estimate roofing materials needed.', icon: HardHatIcon, category: 'Other' },
   { slug: 'tile-calculator', name: 'Tile Calculator', description: 'Estimate tiles needed for an area.', icon: Square, category: 'Other' }, // Generic icon
   { slug: 'mulch-calculator', name: 'Mulch Calculator', description: 'Estimate mulch volume needed.', icon: Sprout, category: 'Other' },
   { slug: 'gravel-calculator', name: 'Gravel Calculator', description: 'Estimate gravel volume needed.', icon: Boxes, category: 'Other' },
   { slug: 'wind-chill-calculator', name: 'Wind Chill Calculator', description: 'Calculate wind chill temperature.', icon: Wind, category: 'Other' },
   { slug: 'heat-index-calculator', name: 'Heat Index Calculator', description: 'Calculate heat index.', icon: ThermometerSun, category: 'Other' },
   { slug: 'dew-point-calculator', name: 'Dew Point Calculator', description: 'Calculate dew point temperature.', icon: Droplets, category: 'Other' },
   { slug: 'bandwidth-calculator', name: 'Bandwidth Calculator', description: 'Calculate data transfer rates.', icon: Wifi, category: 'Other' },
   { slug: 'time-duration-calculator', name: 'Time Duration Calculator', description: 'Calculate duration between times.', icon: Timer, category: 'Other' },
   { slug: 'day-counter', name: 'Day Counter', description: 'Count days between dates.', icon: CalendarDays, category: 'Other' },
   { slug: 'day-of-the-week-calculator', name: 'Day of the Week Calculator', description: 'Find the day of the week for a date.', icon: CalendarDays, category: 'Other' },
];

export const CATEGORIES: { name: CalculatorCategory; icon: LucideIcon }[] = [
  { name: 'Financial', icon: PiggyBank },
  { name: 'Fitness & Health', icon: HeartPulse },
  { name: 'Math', icon: CalculatorIconProp },
  { name: 'Other', icon: Shapes }, // Using Shapes as a generic icon for "Other"
];

// Interface for Currency Data
export interface CurrencyData {
    code: string;
    name: string;
    symbol: string;
    rate: number; // Rate relative to USD
}

// Currency list with mock rates (relative to USD) and symbols
// Mock rates are indicative and should be replaced with a real-time API in production
export const CURRENCIES: CurrencyData[] = [
    { code: "USD", name: "United States Dollar", symbol: "$", rate: 1.0 },
    { code: "EUR", name: "Euro", symbol: "€", rate: 0.92 },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", rate: 150.5 },
    { code: "GBP", name: "British Pound Sterling", symbol: "£", rate: 0.79 },
    { code: "AUD", name: "Australian Dollar", symbol: "A$", rate: 1.52 },
    { code: "CAD", name: "Canadian Dollar", symbol: "C$", rate: 1.35 },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF", rate: 0.88 },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥", rate: 7.19 },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", rate: 7.82 },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", rate: 1.66 },
    { code: "SEK", name: "Swedish Krona", symbol: "kr", rate: 10.45 },
    { code: "KRW", name: "South Korean Won", symbol: "₩", rate: 1330.0 },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$", rate: 1.34 },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr", rate: 10.6 },
    { code: "MXN", name: "Mexican Peso", symbol: "$", rate: 17.1 },
    { code: "INR", name: "Indian Rupee", symbol: "₹", rate: 83.0 },
    { code: "RUB", name: "Russian Ruble", symbol: "₽", rate: 92.0 },
    { code: "ZAR", name: "South African Rand", symbol: "R", rate: 18.9 },
    { code: "TRY", name: "Turkish Lira", symbol: "₺", rate: 31.0 },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", rate: 4.95 },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", rate: 32.0 },
    { code: "DKK", name: "Danish Krone", symbol: "kr", rate: 6.85 },
    { code: "PLN", name: "Polish Złoty", symbol: "zł", rate: 4.00 },
    { code: "THB", name: "Thai Baht", symbol: "฿", rate: 36.5 },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", rate: 15900.0 },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft", rate: 360.0 },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč", rate: 23.0 },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪", rate: 3.70 },
    { code: "CLP", name: "Chilean Peso", symbol: "$", rate: 930.0 },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", rate: 57.5 },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ", rate: 3.67 },
    { code: "COP", name: "Colombian Peso", symbol: "$", rate: 3900.0 },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼", rate: 3.75 },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", rate: 4.70 },
    { code: "RON", name: "Romanian Leu", symbol: "lei", rate: 4.58 },
    // Add all other currencies from the user's list
    { code: "AFN", name: "Afghan Afghani", symbol: "؋", rate: 71.5 },
    { code: "ALL", name: "Albanian Lek", symbol: "L", rate: 95.0 },
    { code: "AMD", name: "Armenian Dram", symbol: "֏", rate: 400.0 },
    { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", rate: 1.79 },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", rate: 830.0 },
    { code: "ARS", name: "Argentine Peso", symbol: "$", rate: 835.0 },
    { code: "AWG", name: "Aruban Florin", symbol: "ƒ", rate: 1.79 },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", rate: 1.70 },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", rate: 1.80 },
    { code: "BBD", name: "Barbadian Dollar", symbol: "$", rate: 2.00 },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", rate: 110.0 },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв", rate: 1.80 },
    { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", rate: 0.38 },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu", rate: 2850.0 },
    { code: "BMD", name: "Bermudan Dollar", symbol: "$", rate: 1.00 },
    { code: "BND", name: "Brunei Dollar", symbol: "$", rate: 1.34 },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", rate: 6.90 },
    { code: "BSD", name: "Bahamian Dollar", symbol: "$", rate: 1.00 },
    { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", rate: 83.0 },
    { code: "BWP", name: "Botswanan Pula", symbol: "P", rate: 13.5 },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br", rate: 3.25 },
    { code: "BZD", name: "Belize Dollar", symbol: "BZ$", rate: 2.00 },
    { code: "CDF", name: "Congolese Franc", symbol: "FC", rate: 2750.0 },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡", rate: 515.0 },
    { code: "CUP", name: "Cuban Peso", symbol: "$", rate: 24.0 },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", rate: 102.0 },
    { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", rate: 177.0 },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$", rate: 58.0 },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", rate: 135.0 },
    { code: "EGP", name: "Egyptian Pound", symbol: "£", rate: 47.5 },
    { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", rate: 15.0 },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br", rate: 57.0 },
    { code: "FJD", name: "Fijian Dollar", symbol: "$", rate: 2.25 },
    { code: "FKP", name: "Falkland Islands Pound", symbol: "£", rate: 0.79 },
    { code: "FOK", name: "Faroese Krona", symbol: "kr", rate: 6.85 },
    { code: "GEL", name: "Georgian Lari", symbol: "₾", rate: 2.70 },
    { code: "GGP", name: "Guernsey Pound", symbol: "£", rate: 0.79 },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", rate: 13.0 },
    { code: "GIP", name: "Gibraltar Pound", symbol: "£", rate: 0.79 },
    { code: "GMD", name: "Gambian Dalasi", symbol: "D", rate: 65.0 },
    { code: "GNF", name: "Guinean Franc", symbol: "FG", rate: 8600.0 },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", rate: 7.80 },
    { code: "GYD", name: "Guyanaese Dollar", symbol: "$", rate: 209.0 },
    { code: "HNL", name: "Honduran Lempira", symbol: "L", rate: 24.7 },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn", rate: 7.0 }, // Pre-Euro
    { code: "HTG", name: "Haitian Gourde", symbol: "G", rate: 132.0 },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", rate: 15900.0 },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪", rate: 3.70 },
    { code: "IMP", name: "Isle of Man Pound", symbol: "£", rate: 0.79 },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", rate: 1310.0 },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼", rate: 42100.0 },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr", rate: 138.0 },
    { code: "JEP", name: "Jersey Pound", symbol: "£", rate: 0.79 },
    { code: "JMD", name: "Jamaican Dollar", symbol: "J$", rate: 155.0 },
    { code: "JOD", name: "Jordanian Dinar", symbol: "JD", rate: 0.71 },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh", rate: 130.0 },
    { code: "KGS", name: "Kyrgystani Som", symbol: "с", rate: 88.0 },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛", rate: 4100.0 },
    { code: "KID", name: "Kiribati Dollar", symbol: "$", rate: 1.52 },
    { code: "KMF", name: "Comorian Franc", symbol: "CF", rate: 450.0 },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", rate: 0.31 },
    { code: "KYD", name: "Cayman Islands Dollar", symbol: "$", rate: 0.83 },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", rate: 445.0 },
    { code: "LAK", name: "Laotian Kip", symbol: "₭", rate: 20500.0 },
    { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", rate: 89500.0 },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", rate: 300.0 },
    { code: "LRD", name: "Liberian Dollar", symbol: "$", rate: 190.0 },
    { code: "LSL", name: "Lesotho Loti", symbol: "L", rate: 18.5 },
    { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", rate: 4.85 },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", rate: 10.0 },
    { code: "MDL", name: "Moldovan Leu", symbol: "L", rate: 17.7 },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", rate: 4400.0 },
    { code: "MKD", name: "Macedonian Denar", symbol: "ден", rate: 56.5 },
    { code: "MMK", name: "Myanma Kyat", symbol: "K", rate: 2100.0 },
    { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", rate: 3400.0 },
    { code: "MOP", name: "Macanese Pataca", symbol: "P", rate: 8.05 },
    { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", rate: 39.5 },
    { code: "MUR", name: "Mauritian Rupee", symbol: "₨", rate: 46.0 },
    { code: "MVR", name: "Maldivian Rufiyaa", symbol: ".ރ", rate: 15.4 },
    { code: "MWK", name: "Malawian Kwacha", symbol: "MK", rate: 1750.0 },
    { code: "MZN", name: "Mozambican Metical", symbol: "MT", rate: 63.5 },
    { code: "NAD", name: "Namibian Dollar", symbol: "$", rate: 18.5 },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦", rate: 1450.0 },
    { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", rate: 36.8 },
    { code: "NPR", name: "Nepalese Rupee", symbol: "₨", rate: 133.0 },
    { code: "OMR", name: "Omani Rial", symbol: "﷼", rate: 0.38 },
    { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", rate: 1.00 },
    { code: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/.", rate: 3.75 },
    { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", rate: 3.80 },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", rate: 57.5 },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨", rate: 278.0 },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", rate: 7250.0 },
    { code: "QAR", name: "Qatari Rial", symbol: "﷼", rate: 3.64 },
    { code: "RSD", name: "Serbian Dinar", symbol: "дин.", rate: 108.0 },
    { code: "RWF", name: "Rwandan Franc", symbol: "RF", rate: 1290.0 },
    { code: "SBD", name: "Solomon Islands Dollar", symbol: "$", rate: 8.35 },
    { code: "SCR", name: "Seychellois Rupee", symbol: "₨", rate: 13.5 },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", rate: 600.0 },
    { code: "SHP", name: "Saint Helena Pound", symbol: "£", rate: 0.79 },
    { code: "SLE", name: "Sierra Leonean Leone (new)", symbol: "Le", rate: 22.5 },
    { code: "SLL", name: "Sierra Leonean Leone (old - might still be seen)", symbol: "Le", rate: 22500.0 },
    { code: "SOS", name: "Somali Shilling", symbol: "S", rate: 570.0 },
    { code: "SRD", name: "Surinamese Dollar", symbol: "$", rate: 35.0 },
    { code: "SSP", name: "South Sudanese Pound", symbol: "£", rate: 130.0 },
    { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", rate: 24.5 },
    { code: "SYP", name: "Syrian Pound", symbol: "£", rate: 13000.0 },
    { code: "SZL", name: "Eswatini Lilangeni", symbol: "L", rate: 18.5 },
    { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", rate: 10.9 },
    { code: "TMT", name: "Turkmenistani Manat", symbol: "T", rate: 3.50 },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", rate: 3.10 },
    { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", rate: 2.35 },
    { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", rate: 6.75 },
    { code: "TVD", name: "Tuvaluan Dollar", symbol: "$", rate: 1.52 },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", rate: 2550.0 },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", rate: 38.0 },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh", rate: 3800.0 },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$U", rate: 39.0 },
    { code: "UZS", name: "Uzbekistan Som", symbol: "лв", rate: 12600.0 },
    { code: "VES", name: "Venezuelan Bolívar Soberano", symbol: "Bs.", rate: 36.3 },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫", rate: 24500.0 },
    { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", rate: 118.0 },
    { code: "WST", name: "Samoan Tala", symbol: "T", rate: 2.75 },
    { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA", rate: 605.0 },
    { code: "XCD", name: "East Caribbean Dollar", symbol: "$", rate: 2.70 },
    // XDR is a special case, rate is approx, symbol might not render well universally
    { code: "XDR", name: "Special Drawing Rights", symbol: "SDR", rate: 0.75 },
    { code: "XOF", name: "CFA Franc BCEAO", symbol: "FCFA", rate: 605.0 },
    { code: "XPF", name: "CFP Franc", symbol: "₣", rate: 110.0 },
    { code: "YER", name: "Yemeni Rial", symbol: "﷼", rate: 250.0 },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", rate: 25.0 },
    { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", rate: 10000.0 }, // Highly volatile
].filter((currency, index, self) =>
    index === self.findIndex((c) => (
        c.code === currency.code // Keep only the first occurrence of each code
    ))
);


// Sort currencies alphabetically by name for display
CURRENCIES.sort((a, b) => a.name.localeCompare(b.name));


export const APP_NAME = "Mathlet";
export const APP_DESCRIPTION = "Your all-in-one calculator for finance, health, and math.";

// Local storage keys
export const HISTORY_STORAGE_KEY = 'mathlet_calculation_history';
export const PROFILE_STORAGE_KEY = 'mathlet_user_profile';
export const FAVORITES_STORAGE_KEY = 'mathlet_favorite_calculators'; // Key for favorites

// Helper to get icon by slug (can be used if needed)
export const getCalculatorIcon = (slug: string): LucideIcon => {
  const calculator = CALCULATORS.find(calc => calc.slug === slug);
  return calculator ? calculator.icon : CalculatorIconProp; // Default icon
};
